#
# Makefile for the Intel(R) i210 ethernet driver
#

obj-$(CONFIG_I210_GIGABIT) += igb.o

igb-objs := igb_main.o e1000_82575.o e1000_i210.o e1000_mac.o e1000_nvm.o e1000_phy.o \
         e1000_manage.o igb_param.o igb_ethtool.o kcompat.o e1000_api.o \
         e1000_mbx.o igb_vmdq.o igb_sysfs.o igb_procfs.o igb_ptp.o

